// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl7Lf-ebKoiydFH_Ayp206VYpM4NrnmOk',
    appId: '1:54634016631:web:7d8c7dd52a2ed0bb873b72',
    messagingSenderId: '54634016631',
    projectId: 'ibls-1',
    authDomain: 'ibls-1.firebaseapp.com',
    storageBucket: 'ibls-1.appspot.com',
    measurementId: 'G-L9S6PQDSCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvbimc_amv_86KH5Ms5xnPxY0opK1jRE',
    appId: '1:54634016631:android:9d0e7bd24aab7961873b72',
    messagingSenderId: '54634016631',
    projectId: 'ibls-1',
    storageBucket: 'ibls-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqKtavFVJouF1Q1YDSfW78v3FZTH46OTA',
    appId: '1:54634016631:ios:45a8f9d0114a83f4873b72',
    messagingSenderId: '54634016631',
    projectId: 'ibls-1',
    storageBucket: 'ibls-1.appspot.com',
    iosClientId: '54634016631-4ddemt5tb5b4u2482iamedgi176ddea4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqKtavFVJouF1Q1YDSfW78v3FZTH46OTA',
    appId: '1:54634016631:ios:45a8f9d0114a83f4873b72',
    messagingSenderId: '54634016631',
    projectId: 'ibls-1',
    storageBucket: 'ibls-1.appspot.com',
    iosClientId: '54634016631-4ddemt5tb5b4u2482iamedgi176ddea4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibls',
  );
}
